// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rixnjglaqyoqdchevppv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpeG5qZ2xhcXlvcWRjaGV2cHB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM4NTIxMzAsImV4cCI6MjA5OTQyODEzMH0.SR38u3xC_U1V78ROnG14XfdIgGb2iN9Y-YErPfWWNTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});